version: '3'

services:
  aspnet:
    image: demoaspnetdocker
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - demo-network
    depends_on:
      - "mysqldemo"

  mysqldemo:
    image: mysql:5.7
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: contacts
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: 123Aa321
    restart: always
    networks:
      - demo-network

networks: 
    demo-network:
        driver: bridge